#!/usr/bin/env bun
/**
 * Build Guest Bundle
 *
 * Compiles the guest runtime (React + reconciler + bridge protocol) into a
 * minified JS string that can be injected into Guest sandbox at runtime.
 *
 * Input:  src/guest-bundle/entry.ts
 * Output: src/guest-bundle/build/bundle.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(import.meta.dir, '..');
const INPUT = path.join(ROOT, 'src/guest-bundle/entry.ts');
const OUTPUT = path.join(ROOT, 'src/guest-bundle/build/bundle.ts');
const TEMP_DIR = '/tmp/rill-build';
const TEMP_FILE = path.join(TEMP_DIR, 'guest-bundle.js');

async function build() {
  console.log('Building Guest Bundle...');
  console.log(`  Input: ${INPUT}`);
  console.log(`  Output: ${OUTPUT}`);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Ensure temp directory exists
  if (!fs.existsSync(TEMP_DIR)) {
    fs.mkdirSync(TEMP_DIR, { recursive: true });
  }

  // Build with Bun
  const result = await Bun.build({
    entrypoints: [INPUT],
    outdir: TEMP_DIR,
    target: 'browser',
    format: 'iife',
    minify: true,
    naming: 'guest-bundle.[ext]',
    external: [], // Bundle everything including react-reconciler
  });

  if (!result.success) {
    console.error('Build failed:');
    for (const log of result.logs) {
      console.error(log);
    }
    process.exit(1);
  }

  // Read the built code
  let code = await Bun.file(TEMP_FILE).text();

  // Prepend Guest environment initialization BEFORE the IIFE
  // This ensures __RILL_GUEST_ENV__ is set BEFORE CallbackRegistry constructor runs
  const GUEST_INIT_CODE = `
// Guest Environment Initialization (prepended by build script)
if(!globalThis.__callbacks)globalThis.__callbacks=new Map();
if(typeof globalThis.__callbackId==="undefined")globalThis.__callbackId=0;
globalThis.__RILL_GUEST_ENV__=true;
if(typeof globalThis.__registerCallback!=="function")globalThis.__registerCallback=function(fn){var id="fn_"+ ++globalThis.__callbackId;globalThis.__callbacks.set(id,fn);return id;};
if(typeof globalThis.__invokeCallback!=="function")globalThis.__invokeCallback=function(fnId,args){var fn=globalThis.__callbacks.get(fnId);if(fn)return fn.apply(null,args||[]);console.warn("[rill] Callback not found:",fnId);};
`;

  // Insert after the opening of IIFE: (()=>{ ... })()
  // The built code starts with "(()=>{" so we insert after that
  if (code.startsWith('(()=>{')) {
    code = `(()=>{${GUEST_INIT_CODE}${code.slice(6)}`;
  } else {
    // Fallback: just prepend
    code = GUEST_INIT_CODE + code;
  }

  const sizeKB = (code.length / 1024).toFixed(2);

  // Generate the TypeScript file with the embedded code
  const output = `/**
 * Guest Bundle Code (Auto-generated)
 *
 * DO NOT EDIT - Generated by scripts/build-guest-bundle.ts
 * Run: bun scripts/build-guest-bundle.ts
 *
 * This code is injected into Guest sandbox to provide:
 * - React 19 runtime
 * - Custom reconciler (react-reconciler)
 * - Bridge protocol (serialization, callbacks)
 *
 * It registers RillReconciler on globalThis with render/unmount/unmountAll.
 *
 * Size: ${sizeKB} KB (minified)
 */

export const GUEST_BUNDLE_CODE = ${JSON.stringify(code)};

/**
 * Size in bytes (for monitoring)
 */
export const GUEST_BUNDLE_SIZE = ${code.length};
`;

  fs.writeFileSync(OUTPUT, output);

  console.log(`✓ Generated ${OUTPUT}`);
  console.log(`  Size: ${sizeKB} KB (${code.length} bytes)`);

  // Cleanup
  try {
    fs.unlinkSync(TEMP_FILE);
  } catch {
    // Ignore cleanup errors
  }
}

build().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
